config/routes.rb
Rails.application.routes.draw do
  resources :extern_expenses, :companies, :credit_invoices, :credit_notes, :national_expenses, :trip_expenses,
            :employees, :payments

  post 'make_report', to: 'reports#make_report'

  get 'payment_report', to: 'employees#payment_report'

  get '/payments/:id/order', to: 'orders#new', as: :new_order

  get 'restart', to: 'site_configs#restart'

  resources :reports, only: :show
  resources :site_configs, only: %i[index update]

  resources :orders, only: %i[show create]

  resources :employees do
    resources :payments
    resources :papers
  end

  resources :trucks do
    resources :events
    resources :papers
  end

  resources :users, except: :show

  resources :sessions, only: %i[new create destroy]

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/profile', to: 'users#show', via: 'get'
  match '/main', to: 'mainpage#index', via: 'get'

  root 'mainpage#index'

  get '/trucks/:id/cnotes', to: 'trucks#cnotes', as: :cnotes

end

app/models/employee.rb
# frozen_string_literal: true

class Employee < ActiveRecord::Base
  before_save :set_names

  validates :first_name, :last_name, :cnp, presence: true

  has_many :payments
  has_many :papers, as: :document, dependent: :destroy
  belongs_to :created_by, foreign_key: 'create_id', class_name: 'User', optional: true
  belongs_to :updated_by, foreign_key: 'update_id', class_name: 'User', optional: true

  accepts_nested_attributes_for :papers, allow_destroy: true

  def name
    "#{first_name} #{last_name}"
  end

  private

  def set_names
    self.first_name = first_name.capitalize
    self.last_name = last_name.capitalize
  end
end

app/controllers/employees_controller.rb
# frozen_string_literal: true

class EmployeesController < ApplicationController
  include UserInfo

  before_action :set_employee, only: %i[show edit update destroy]
  before_action :signed_in_user
  before_action :user_activated

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all.paginate(page: params[:page], per_page: 8).order('cnp ASC')
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit; end

  def show; end

  # generate monthly payments reports
  def payment_report
    month = params['month'].empty? ? Date.today : params['month']
    respond_to do |format|
      format.html do
        pdf = PaymentReportPdf.new(month)
        send_data pdf.render, filename: "diurne #{month}.pdf",
                              type: 'application/pdf',
                              disposition: 'inline'
      end
    end
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employees_path, flash: { success: 'Employee was successfully created.' } }
        format.json { render action: 'show', status: :created, location: @employee }
      else
        format.html { render action: 'new' }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, flash: { succes: 'Employee was successfully updated.' } }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_employee
    @employee = Employee.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :cnp, :bank_ron, :bank_eur, :activ)
  end
end

app/helpers/employees_helper.rb
# frozen_string_literal: true

module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= bootstrap_form_for(@employee, layout: :horizontal, label_col: 'col-sm-3', control_col: 'col-sm-7') do |f| %>
    <%= f.alert_message 'Please fix the errors below.', error_summary: false %>
    <%= f.text_field :first_name %>
    <%= f.text_field :last_name %>
    <%= f.text_field :cnp %>
    <%= f.submit 'Submit', class: 'btn btn-success' %>
    <%= link_to 'Back', employees_path, class: 'btn btn-danger' %>
<% end %>

app/views/employees/edit.html.erb
<h2 class="title">Editing employee</h2>
<div class="container-fluid">
  <%= render 'form' %>
</div>

app/views/employees/index.html.erb
<h2 class="title">Listing employees</h2>
<div class="container-fluid">

  <% if flash %>
      <% flash.each do |k, v| %>
          <%= alert(k, v) %>
      <% end %>
  <% end %>

  <table class="table table-hover table-condensed">
    <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>CNP</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <% unless @employees.nil? %>
        <% @employees.each do |employee| %>
            <tr>
              <td><%= employee.first_name %></td>
              <td><%= employee.last_name %></td>
              <td><%= employee.cnp %></td>
              <td class="btn-group btn-group-xm">
                <%= link_to 'Papers', employee_papers_path(employee), class: 'btn btn-info' %>
                <%= link_to 'Payments', employee_payments_path(employee), class: 'btn btn-info' %>
                <%= link_to 'Edit', edit_employee_path(employee), class: 'btn btn-info' %>
                <%= link_to 'Destroy', employee, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' %></td>
            </tr>
        <% end %>
    <% end %>
    </tbody>
  </table>

  <div class="button-container">
    <%= link_to 'New Employee', new_employee_path, class: 'btn btn-primary' %>
  </div>
  <div class="button-container">
    <%= will_paginate @employees, renderer: BootstrapPagination::Rails %>
  </div>
  <div class="button-container">
    <%= bootstrap_form_tag(url: payment_report_path, method: 'get') do |f| %>
        <%= f.text_field :month, hide_label: true, placeholder: 'Select a month', 'data-provide' => 'monthpicker', wrapper: {class: 'gen_payments_btn'} %>
        <%= f.submit 'Generate Raport', class: 'btn btn-info' %>
    <% end %>
  </div>

</div>
<div id="modal" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>

app/views/employees/new.html.erb
<h2 class="title">New employee</h2>
<div class="container-fluid">
  <%= render 'form' %>
</div>