config/routes.rb
Rails.application.routes.draw do
  resources :extern_expenses, :companies, :credit_invoices, :credit_notes, :national_expenses, :trip_expenses,
            :employees, :payments

  post 'make_report', to: 'reports#make_report'

  get 'payment_report', to: 'employees#payment_report'

  get '/payments/:id/order', to: 'orders#new', as: :new_order

  get 'restart', to: 'site_configs#restart'

  resources :reports, only: :show
  resources :site_configs, only: %i[index update]

  resources :orders, only: %i[show create]

  resources :employees do
    resources :payments
    resources :papers
  end

  resources :trucks do
    resources :events
    resources :papers
  end

  resources :users, except: :show

  resources :sessions, only: %i[new create destroy]

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/profile', to: 'users#show', via: 'get'
  match '/main', to: 'mainpage#index', via: 'get'

  root 'mainpage#index'

  get '/trucks/:id/cnotes', to: 'trucks#cnotes', as: :cnotes

end

app/models/truck.rb
# frozen_string_literal: true

class Truck < ActiveRecord::Base
  before_save :cap

  validates :registration, :vin, presence: true
  validates :vin, uniqueness: true
  # validates vin length

  has_many :credit_notes
  has_many :events
  has_many :papers, as: :document, dependent: :destroy
  belongs_to :created_by, foreign_key: 'create_id', class_name: 'User', optional: true
  belongs_to :updated_by, foreign_key: 'update_id', class_name: 'User', optional: true

  accepts_nested_attributes_for :papers, allow_destroy: true

  protected

  def cap
    self.registration = registration.upcase
    self.vin = vin.upcase
  end
end

app/controllers/trucks_controller.rb
# frozen_string_literal: true

class TrucksController < ApplicationController
  include UserInfo

  before_action :set_truck, only: %i[show edit update destroy]
  before_action :signed_in_user
  before_action :user_activated

  # GET /trucks
  # GET /trucks.json
  def index
    @trucks = Truck.order('sold ASC, truck DESC').paginate(page: params[:page], per_page: 8)
  end

  # GET /trucks/1
  # GET /trucks/1.json
  def show; end

  def cnotes
    @truck = Truck.find(params[:id])
    @q = @truck.credit_notes.ransack(params[:q])
    @cn = @q.result(distinct: true).order('order_nr ASC').paginate(page: params[:page], per_page: 8)
  end

  # GET /trucks/new
  def new
    @truck = Truck.new
  end

  # GET /trucks/1/edit
  def edit; end

  # POST /trucks
  # POST /trucks.json
  def create
    @truck = Truck.new(truck_params)
    on_create(@truck)
    respond_to do |format|
      if @truck.save
        format.html { redirect_to truck_papers_path(@truck), flash: { success: 'Truck was successfully created.' } }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /trucks/1
  # PATCH/PUT /trucks/1.json
  def update
    on_update(@truck)
    respond_to do |format|
      if @truck.update(truck_params)
        format.html { redirect_to truck_papers_path(@truck), flash: { success: 'Truck was successfully updated.' } }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /trucks/1
  # DELETE /trucks/1.json
  def destroy
    @truck.destroy
    respond_to do |format|
      format.html { redirect_to trucks_url, flash: { success: 'Truck was successfully deleted.' } }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_truck
    @truck = Truck.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def truck_params
    params.require(:truck).permit(:registration, :vin, :truck, :sold, papers_attributes: [:id, :description, :expire, :comments, :_destroy, attachments_attributes: %i[id file _destroy]])
  end
end

app/helpers/trucks_helper.rb
# frozen_string_literal: true

module TrucksHelper
end

app/views/trucks/_form.html.erb
<%= bootstrap_form_for(@truck, layout: :horizontal, label_col: 'col-sm-3', control_col: 'col-sm-7') do |f| %>
    <%= f.alert_message 'Please fix the errors below.', error_summary: false %>
    <%= f.text_field :registration %>
    <%= f.text_field :vin %>
    <%= f.form_group :truck, label: {text: 'Truck?'} do %>
        <%= f.check_box :truck, label: '' %>
    <% end %>
    <%= f.form_group :sold, label: {text: 'Sold?'} do %>
        <%= f.check_box :sold, label: '' %>
    <% end %>
    <div class="modal-footer">
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
      <button class="btn btn-danger" data-dismiss="modal" aria-hidden="true">Cancel</button>
    </div>
<% end %>

app/views/trucks/cnotes.html.erb
<h2 class="title">Listing <%= @truck.registration %> Credit Notes</h2>
<div class="container-fluid">

  <% if flash %>
      <% flash.each do |k, v| %>
          <%= alert(k, v) %>
      <% end %>
  <% end %>

  <table class="table table-hover table-condensed">
    <thead>
    <tr>
      <th><%= sort_link(@q, :order_nr, 'Order Nr', default_order: :asc) %></th>
      <th>Number</th>
      <th>Start</th>
      <th>Stop</th>
      <th class="middle">Week</th>
      <th class="t_right">Value</th>
      <th class="t_middle">Paid</th>
      <th class="t_middle">Notes</th>
      <th><%= render 'credit_notes/search' %></th>
    </tr>
    </thead>

    <tbody>
    <% @cn.each do |cn| %>
        <tr>
          <td><%= best_in_place cn, :order_nr %></td>
          <td><%= cn.number %></td>
          <td><%= cn.start %></td>
          <td><%= cn.stop %></td>
          <td class="t_middle"><%= cn.week %></td>
          <td class="t_value"><%= number_to_currency(cn.value, unit: cn.currency, locale: 'ro') %></td>
          <td class="t_middle"><%= raw paid(cn) %></td>
          <td class="t_middle"><%= cn.notes %></td>
          <td class="btn-group btn-group-xm">
            <%= file_state(cn, 'Show') %>
            <%= link_to 'Edit', edit_credit_note_path(cn), class: 'btn btn-info' %>
            <%= link_to 'Destroy', cn, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= will_paginate @cn, renderer: BootstrapPagination::Rails %>
</div>

app/views/trucks/edit.js.erb
$(".modal-content").html("<%= escape_javascript(render 'modal/modal') %>");
$(document).ready(function () {
  $('#myModalLabel').text("Editing truck...");
});

app/views/trucks/edit_truck_paper.js.erb
$("#paper-modal").html("<%= escape_javascript(render 'trucks/modal') %>");
$(document).ready(function() {
    $('.datepicker').datepicker({
        format: "yyyy-mm-dd",
        todayBtn: "linked",
        orientation: "top left",
        autoclose: true,
        todayHighlight: true
    });
});

app/views/trucks/index.html.erb
<h2 class="title">Listing trucks</h2>
<div class="container-fluid">

  <% if flash %>
      <% flash.each do |k, v| %>
          <%= alert(k, v) %>
      <% end %>
  <% end %>

  <table class="table table-hover table-condensed">
    <thead>
    <tr>
      <th style="width: 40%;">VIN</th>
      <th style="width: 20%;">Registration</th>
      <th style="width: 40%;"></th>
    </tr>
    </thead>

    <tbody>
    <% @trucks.each do |truck| %>
        <tr>
          <td><%= truck.vin %></td>
          <td><%= truck.registration %></td>
          <td class="btn-group btn-group-xm">
            <%= link_to 'Details', truck_papers_path(truck), class: 'btn btn-info' %>
            <%= link_to 'Credit Notes', cnotes_path(truck), class: 'btn btn-info' %>
            <%= link_to 'Events', truck_events_path(truck), class: 'btn btn-info' %>
            <%= link_to 'Edit', edit_truck_path(truck), {:remote => true, data: {toggle: 'modal', target: '#modal', backdrop: 'static'}, class: 'btn btn-info'} %>
            <%= link_to 'Destroy', truck, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <div class="button-container">
    <%= link_to 'Add Truck', new_truck_path, {:remote => true, data: {toggle: 'modal', target: '#modal', backdrop: 'static'}, class: 'btn btn-primary'} %>
  </div>
  <div class="button-container">
    <%= will_paginate @trucks, renderer: BootstrapPagination::Rails %>
  </div>

</div>

<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>

app/views/trucks/new.js.erb
$(".modal-content").html("<%= escape_javascript(render 'modal/modal') %>");
$(document).ready(function () {
  $('#myModalLabel').text("Add new truck...");
});

app/views/trucks/new_truck_paper.js.erb
$("#paper-modal").html("<%= escape_javascript(render 'trucks/modal') %>");