config/routes.rb
Rails.application.routes.draw do
  resources :extern_expenses, :companies, :credit_invoices, :credit_notes, :national_expenses, :trip_expenses,
            :employees, :payments

  post 'make_report', to: 'reports#make_report'

  get 'payment_report', to: 'employees#payment_report'

  get '/payments/:id/order', to: 'orders#new', as: :new_order

  get 'restart', to: 'site_configs#restart'

  resources :reports, only: :show
  resources :site_configs, only: %i[index update]

  resources :orders, only: %i[show create]

  resources :employees do
    resources :payments
    resources :papers
  end

  resources :trucks do
    resources :events
    resources :papers
  end

  resources :users, except: :show

  resources :sessions, only: %i[new create destroy]

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/profile', to: 'users#show', via: 'get'
  match '/main', to: 'mainpage#index', via: 'get'

  root 'mainpage#index'

  get '/trucks/:id/cnotes', to: 'trucks#cnotes', as: :cnotes

end

app/models/company.rb
# frozen_string_literal: true

class Company < ActiveRecord::Base
  before_create :find_company

  has_many :credit_invoices
  has_many :national_expenses
  has_many :extern_expenses
  belongs_to :created_by, foreign_key: 'create_id', class_name: 'User', optional: true
  belongs_to :updated_by, foreign_key: 'update_id', class_name: 'User', optional: true

  private

  def find_company
    if country == 'RO'
      national
    else
      international
    end
  end

  def national
    response = HTTParty.get(
      "https://api.openapi.ro/api/companies/#{vat}",
      { headers: { 'x-api-key': ENV['OPENAPI_KEY'] } }
    )

    if response.code == 200
      self.name = response['denumire']
      self.registration = response['numar_reg_com']
      self.vat = if response['tva'].nil?
                   response['cif']
                 else
                   "RO#{response['cif']}"
                 end
      self.address = "#{response['adresa']}, #{response['judet']}, Romania"
      self.phone = response['telefon']
    else
      self.name = '#'
    end
    nil
  end

  def international
    company = if country == 'GR'
                Valvat.new("EL#{vat}").exists?(detail: true)
              else
                Valvat.new("#{country}#{vat}").exists?(detail: true)
              end

    if company == false || company.nil? || company[:name].nil? || company[:address].nil?
      self.name = '#'
    else
      self.name = company[:name].titleize
      self.vat = "EL#{vat}" if country == 'GR'
      self.address = company[:address]
      self.vies_valid = true
    end
  end
end

app/controllers/companies_controller.rb
# frozen_string_literal: true

class CompaniesController < ApplicationController
  include UserInfo

  before_action :set_company, only: %i[show edit update destroy]
  before_action :signed_in_user
  before_action :user_activated

  # GET /companies
  # GET /companies.json
  def index
    @q = Company.ransack(params[:q])
    @companies = @q.result(distinct: true)
                   .paginate(page: params[:page], per_page: 8)
                   .order('name ASC')
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit; end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    on_create(@company)
    respond_to do |format|
      if @company.save
        format.html do
          redirect_to companies_url,
                      flash: { success: 'Company was successfully created.' }
        end
        format.json do
          render action: 'show',
                 status: :created, location: @company
        end
      else
        format.html { render action: 'new' }
        format.json do
          render json: @company.errors,
                 status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    on_update(@company)
    respond_to do |format|
      if @company.update(company_params)
        format.html do
          redirect_to companies_url,
                      flash: { success: 'Company was successfully updated.' }
        end
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json do
          render json: @company.errors,
                 status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html do
        redirect_to companies_url,
                    flash: { success: 'Company was successfully deleted.' }
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_company
    @company = Company.find(params[:id])
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def company_params
    params.require(:company).permit(
      :name, :registration, :vat, :country,
      :vies_valid, :address, :acc_ron,
      :acc_eur, :bank, :capital, :phone
    )
  end
end

app/helpers/companies_helper.rb
# frozen_string_literal: true

module CompaniesHelper
  def eu_countries_list
    full_list = ISO3166::Country.all
    list = []
    full_list.each do |x|
      list.push(x.alpha2) if x.in_eu?
    end
    list
  end
end

app/views/companies/_form.html.erb
<%= bootstrap_form_for(@company, layout: :horizontal, label_col: 'col-sm-3', control_col: 'col-sm-7') do |f| %>
    <%= f.text_field :registration, disabled: true %>
    <%= f.text_field :vat, disabled: true %>
    <%= f.text_field :address, disabled: true %>
    <%= f.text_field :acc_ron, disabled: true, label: 'RON Account' %>
    <%= f.text_field :acc_eur, disabled: true, label: 'EUR Account' %>
    <%= f.text_field :bank, disabled: true %>
    <%= f.text_field :capital, disabled: true %>
    <%= f.phone_field :phone, disabled: true %>
    <%= f.email_field :email, disabled: true %>
    <%= f.text_field :contact, disabled: true %>
    <div class="modal-footer">
      <button class="btn btn-danger" data-dismiss="modal" aria-hidden="true">Cancel</button>
    </div>
<% end %>

app/views/companies/_form2.html.erb
<div id="toggle_comp_info">
  <%= bootstrap_form_for(@company, layout: :horizontal, label_col: 'col-sm-1', control_col: 'col-sm-5') do |f| %>
      <%= f.alert_message 'Please fix the errors below.', error_summary: false %>
      <%= f.text_field :name %>
      <%= f.text_field :registration %>
      <%= f.text_field :vat %>
      <%= f.form_group :vies, label: {text: 'Vies valid?'} do %>
          <%= f.check_box :vies_valid, label: '' %>
      <% end %>
      <%= f.form_group :country, label: {text: 'Country'} do %>
          <%= f.country_select :country, {only: eu_countries_list}, class: 'form-control' %>
      <% end %>
      <%= f.text_field :address %>
      <%= f.text_field :acc_ron, label: 'RON Account' %>
      <%= f.text_field :acc_eur, label: 'EUR Account' %>
      <%= f.text_field :bank %>
      <%= f.text_field :capital %>
      <%= f.phone_field :phone %>
      <%= f.email_field :email %>
      <%= f.text_field :contact %>
      <%= f.submit 'Submit', class: 'btn btn-success' %>
      <%= link_to 'Back', companies_path, class: 'btn btn-danger' %>
  <% end %>
</div>

app/views/companies/_form3.html.erb
<%= bootstrap_form_for(@company, layout: :inline, label_col: 'col-sm-3', control_col: 'col-sm-7') do |f| %>
    <%= f.country_select :country, {selected: 'RO', only: eu_countries_list}, class: 'form-control' %>
    <%= f.number_field :vat, hide_label: true, placeholder: 'VAT number' %>
    <div class="modal-footer">
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
      <button class="btn btn-danger" data-dismiss="modal" aria-hidden="true">Cancel</button>
    </div>
<% end %>

app/views/companies/_modal.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h3 id="myModalLabel"></h3>
</div>
<div class="modal-body">
  <%= render partial: 'form3' %>
</div>

app/views/companies/_search.html.erb
<%= search_form_for @q, html: {class: 'form-inline'} do |f| %>
    <%= f.search_field :name_cont, placeholder: 'Search', type: 'search', class: 'form-control search_input' %>
<% end %>

app/views/companies/edit.html.erb
<h2 class="title">Editing company</h2>
<div class="container-fluid">
  <%= render 'form2' %>
</div>

app/views/companies/index.html.erb
<h2 class="title">Listing companies</h2>
<div class="container-fluid">

  <% if flash %>
      <% flash.each do |k, v| %>
          <%= alert(k, v) %>
      <% end %>
  <% end %>

  <table class="table table-hover table-condensed">
    <thead>
    <tr>
      <th>Name</th>
      <th>VAT id</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Contact</th>
      <th><%= render 'search' %></th>
    </tr>
    </thead>

    <tbody>
    <% @companies.each do |company| %>
        <tr>
          <td><%= company.name %></td>
          <td><%= company.vat %></td>
          <td><%= company.phone %></td>
          <td><%= company.email %></td>
          <td><%= company.contact %></td>
          <td class="btn-group btn-group-xm">
            <%= link_to 'Show', company, {:remote => true, data: {toggle: 'modal', target: '#modal'}, class: 'btn btn-info'} %>
            <%= link_to 'Edit', edit_company_path(company), class: 'btn btn-info' %>
            <%= link_to 'Destroy', company, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <div class="button-container">
    <%= link_to 'New Company', new_company_path, {:remote => true, data: {toggle: 'modal', target: '#modal', backdrop: 'static'}, class: 'btn btn-primary'} %>
  </div>
  <div class="button-container">
    <%= will_paginate @companies, renderer: BootstrapPagination::Rails %>
  </div>

</div>

<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>

app/views/companies/new.js.erb
$(".modal-content").html("<%= escape_javascript(render 'modal') %>");
$(document).ready(function () {
  $('#myModalLabel').text("Add new company...");
});

app/views/companies/show.js.erb
$(".modal-content").html("<%= escape_javascript(render 'modal/modal') %>");
$(document).ready(function () {
  var header = 'Info for: ' + "<%= @company.name %>";
  $('#myModalLabel').html(header);
});