config/routes.rb
Rails.application.routes.draw do
  resources :extern_expenses, :companies, :credit_invoices, :credit_notes, :national_expenses, :trip_expenses,
            :employees, :payments

  post 'make_report', to: 'reports#make_report'

  get 'payment_report', to: 'employees#payment_report'

  get '/payments/:id/order', to: 'orders#new', as: :new_order

  get 'restart', to: 'site_configs#restart'

  resources :reports, only: :show
  resources :site_configs, only: %i[index update]

  resources :orders, only: %i[show create]

  resources :employees do
    resources :payments
    resources :papers
  end

  resources :trucks do
    resources :events
    resources :papers
  end

  resources :users, except: :show

  resources :sessions, only: %i[new create destroy]

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/profile', to: 'users#show', via: 'get'
  match '/main', to: 'mainpage#index', via: 'get'

  root 'mainpage#index'

  get '/trucks/:id/cnotes', to: 'trucks#cnotes', as: :cnotes

end

app/models/paper.rb
# frozen_string_literal: true

class Paper < ActiveRecord::Base
  include ImageConvert

  after_create :cap
  before_create :convert
  before_update :convert

  belongs_to :document, polymorphic: true
  belongs_to :created_by, foreign_key: 'create_id', class_name: 'User', optional: true
  belongs_to :updated_by, foreign_key: 'update_id', class_name: 'User', optional: true

  has_many :attachments, as: :attachable, dependent: :destroy

  accepts_nested_attributes_for :attachments, allow_destroy: true

  validates :description, presence: true

  protected

  def cap
    self.description = description.capitalize unless description.nil?
    self.comments = comments.capitalize unless comments.nil?
  end
end

app/controllers/papers_controller.rb
# frozen_string_literal: true

class PapersController < ApplicationController
  include UserInfo

  before_action :set_paper, only: %i[show edit update destroy]
  before_action :signed_in_user
  before_action :user_activated
  before_action :update_file, only: :update
  before_action :find_document

  # GET /papers
  # GET /papers.json
  def index
    @papers = @document.papers.paginate(page: params[:page], per_page: 14).order('expire ASC').order('description ASC')
  end

  # GET /papers/1
  # GET /papers/1.json
  def show
    # @papers = Paper.all.paginate(:page => params[:page], :per_page => 8).order('expire ASC').order('description ASC') FIX
  end

  # GET /papers/new
  def new
    @paper = @document.papers.build
  end

  # GET /papers/1/edit
  def edit
    @paper = Paper.find(params[:id])
    @truck = @paper.document # FIX
  end

  # POST /papers
  # POST /papers.json
  def create
    @paper = @document.papers.build
    @paper.update(paper_params)
    on_create(@paper)
    respond_to do |format|
      if @document.save
        format.html { redirect_to parent_url(@document), flash: { success: 'Paper was successfully created.' } }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /papers/1
  # PATCH/PUT /papers/1.json
  def update
    @paper = Paper.find(params[:id])
    on_update(@paper)
    respond_to do |format|
      if @paper.update(paper_params)
        format.html { redirect_to parent_url(@document), flash: { success: 'Paper was successfully updated.' } }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /papers/1
  # DELETE /papers/1.json
  def destroy
    @paper.destroy
    respond_to do |format|
      format.html { redirect_to parent_url(@document), flash: { success: 'Paper was successfully deleted.' } }
    end
  end

  private

  # set document depending of class
  def find_document
    klass = [Truck, Employee].detect { |c| params["#{c.name.underscore}_id"] }
    @document = klass.find(params["#{klass.name.underscore}_id"])
  end

  # set proper url path
  def parent_url(parent)
    if params[:truck_id]
      truck_papers_path(parent)
    elsif params[:employee_id]
      employee_papers_path(parent)
    end
  end

  # replace file on update
  def update_file
    # check to see if there is a file to replace or just create a new record
    return if Paper.find(params[:id]).attachments.empty?

    # check to see if the user wants to replace the file or just edit paper attributes
    return if paper_params[:attachments_attributes]['0'][:id].nil?

    # Destroy the old record and create a new one with the same id
    # because carrier doesn't support editing file attribute
    Paper.find(params[:id]).attachments.destroy_all
    a = @paper.attachments.new
    a.update(id: paper_params[:attachments_attributes]['0'][:id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_paper
    @paper = Paper.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def paper_params
    params.require(:paper).permit(:description, :expire, :is_info, :comments, attachments_attributes: %i[id file _destroy])
  end
end

app/helpers/papers_helper.rb
# frozen_string_literal: true

module PapersHelper
  def expire_row(date)
    today = Time.now.to_date
    return if date.nil?

    diff = (date - today).to_i
    if diff.zero?
      "class='error tip' data-title='This document will expire today.'"
    elsif diff.negative?
      "class='error tip' data-title='This document has expired #{pluralize(diff.abs, 'day')} ago.'"
    elsif diff.positive? && diff <= 7
      "class='error tip' data-title='This document will expire in #{pluralize(diff.abs, 'day')}.'"
    elsif diff > 7 && diff < 30
      "class='warning tip' data-title='This document will expire in #{diff} days.'"
    end
  end

  def path_info(path, action, p)
    if path == 'truck'
      if action == 'edit'
        edit_truck_paper_path(p.document, p)
      else
        truck_paper_path(p.document, p)
      end
    else
      if action == 'edit'
        edit_employee_paper_path(p.document, p)
      else
        employee_paper_path(p.document, p)
      end
    end
  end
end

app/views/papers/_employee.html.erb
<div class="container-fluid">
  <% if flash %>
      <% flash.each do |k, v| %>
          <%= alert(k, v) %>
      <% end %>
  <% end %>

  <h3 style="text-align: center">
    <strong>Documents for: </strong><%= @document.name %>
  </h3>

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#papers" aria-controls="papers" role="tab" data-toggle="tab">Documents</a></li>
    <li role="presentation"><a href="#info" aria-controls="info" role="tab" data-toggle="tab">Info</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane fade in active" id="papers">
      <%= render partial: 'papers/paper_table', locals: {papers: @papers.where(is_info: false), model_path: 'employee'} %>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="info">
      <%= render partial: 'papers/paper_table', locals: {papers: @papers.where(is_info: true), model_path: 'employee'} %>
    </div>
  </div>

  <div class="button-container">
    <%= link_to 'Add new', new_truck_paper_path(@document), {:remote => true, data: {toggle: 'modal', target: '#modal', backdrop: 'static'}, class: 'btn btn-primary'} %>
  </div>
  <div class="button-container">
    <%= will_paginate @papers, renderer: BootstrapPagination::Rails %>
  </div>

  <div class="button-container">
    <%= link_to 'Add paper', new_employee_paper_path(@document), {:remote => true, data: {toggle: 'modal', target: '#modal', backdrop: 'static'}, class: 'btn btn-primary'} %>
  </div>
  <div class="button-container">
    <%= will_paginate @papers, renderer: BootstrapPagination::Rails %>
  </div>
</div>

<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/papers/_form.html.erb
<%= bootstrap_nested_form_for([@document, @paper], layout: :horizontal, label_col: 'col-sm-3', control_col: 'col-sm-7') do |p| %>
    <%= p.alert_message 'Please fix the errors below.', error_summary: false %>
    <%= p.text_field :description %>
    <%= p.text_field :expire, :value => "#{p.object.expire.strftime('%d/%m/%Y') unless p.object.new_record? || p.object.expire.nil? }", 'data-provide' => 'datepicker', 'data-date-format' => 'dd/mm/yyyy', 'data-date-autoclose' => 'true' %>
    <%= p.form_group :paid, label: {text: 'It is info?'} do %>
        <%= p.check_box :is_info, label: '' %>
    <% end %>
    <%= p.text_field :comments %>
    <%= p.fields_for :attachments do |a| %>
        <div class="button-container">
          <%= a.file_field :file, hide_label: true, label_col: 'col-sm-0' %>
        </div>
        <div class="button-container">
          <%= a.link_to_remove '', class: 'glyphicon glyphicon-remove' %>
        </div>
    <% end %>
    <%= p.link_to_add 'Add file', :attachments, class: 'btn btn-info' %>
    <div class="modal-footer">
      <%= p.submit 'Submit', class: 'btn btn-primary' %>
      <button class="btn btn-danger" data-dismiss="modal" aria-hidden="true">Cancel</button>
    </div>
<% end %>

app/views/papers/_modal.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h3 id="myModalLabel">Add new document...</h3>
</div>
<div class="modal-body">
  <%= render partial: 'paper' %>
</div>

app/views/papers/_paper.html.erb
<%= simple_nested_form_for [@truck, @paper], :html => {class: 'form-horizontal'} do |p| %>
	<%= p.input :description %>
	<%= p.input :expire, as: :string, input_html: {class: 'datepicker'} %>
	<%= p.input :comments %>
	<%= p.simple_fields_for :attachments do |a| %>
        <%= a.file_field :file %>
        <%= a.link_to_remove "", class: "icon-remove" %>
    <% end %>
    <%= p.link_to_add "Add file", :attachments, class: "btn btn-info" %>
    <div class="modal-footer">
  		<%= p.button :submit, class: "btn btn-primary" %>
  	<button class="btn btn-danger" data-dismiss="modal" aria-hidden="true">Cancel</button>
</div>
<% end %>

app/views/papers/_paper_table.erb
<table class="table table-hover table-condensed">
  <thead>
  <tr>
    <th style="width: 30%;">Paper</th>
    <th style="width: 10%;">Expire</th>
    <th style="width: 40%; text-align: center;">Comments</th>
    <th style="width: 20%;"></th>
  </tr>
  </thead>
  <tbody>
  <% unless papers.nil? %>
      <% papers.each do |p| %>
          <tr <%= raw expire_row(p.expire) %> >
            <td><%= p.description %></td>
            <td><%= p.expire %></td>
            <td class="td.t_center"><%= p.comments %></td>
            <td class="btn-group btn-group-xm">
              <%= file_state(p, 'Show') %>
              <%= link_to 'Edit', path_info(model_path, 'edit', p), {:remote => true, data: {toggle: 'modal', target: '#modal'}, class: 'btn btn-info'} %>
              <%= link_to 'Destroy', path_info(model_path, 'destroy', p), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' %>
            </td>
          </tr>
      <% end %>
  <% end %>
  </tbody>
</table>

app/views/papers/_truck.html.erb
<div class="container">
  <% if flash %>
      <% flash.each do |k, v| %>
          <%= alert(k, v) %>
      <% end %>
  <% end %>

  <h3 style="text-align: center">
    <strong>Registration:</strong> <%= link_to @document.registration, edit_truck_path(@document), {:remote => true, data: {toggle: 'modal', target: '#modal', backdrop: 'static'}} %>
    (VIN: <%= @document.vin %>)
  </h3>

  <h4 style="text-align: center">
    View <%= link_to 'Credit Notes', cnotes_path(@document) %> or <%= link_to 'Events', truck_events_path(@document) %>.
  </h4>

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#papers" aria-controls="papers" role="tab" data-toggle="tab">Documents</a></li>
    <li role="presentation"><a href="#info" aria-controls="info" role="tab" data-toggle="tab">Info</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane fade in active" id="papers">
      <%= render partial: 'papers/paper_table', locals: {papers: @papers.where(is_info: false), model_path: 'truck'} %>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="info">
      <%= render partial: 'papers/paper_table', locals: {papers: @papers.where(is_info: true), model_path: 'truck'} %>
    </div>
  </div>

  <div class="button-container">
    <%= link_to 'Add new', new_truck_paper_path(@document), {:remote => true, data: {toggle: 'modal', target: '#modal', backdrop: 'static'}, class: 'btn btn-primary'} %>
  </div>
  <div class="button-container">
    <%= will_paginate @papers, renderer: BootstrapPagination::Rails %>
  </div>

</div>


<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/papers/edit.js.erb
$(".modal-content").html("<%= escape_javascript(render 'modal/modal') %>");
$(document).ready(function () {
  $('#myModalLabel').text("Editing paper...");
});

app/views/papers/index.html.erb
<% if @document.class.to_s == 'Truck' %>
    <%= render 'truck' %>
<% else %>
    <%= render 'employee' %>
<% end %>

app/views/papers/new.js.erb
$(".modal-content").html("<%= escape_javascript(render 'modal/modal') %>");
$(document).ready(function () {
  $('#myModalLabel').text("Add new paper...");
});